services:
  - type: web
    name: mini-ecommerce-api
    runtime: docker
    rootDir: server
    dockerfilePath: ./Dockerfile
    dockerCommand: sh -c 'npm run migration:run:prod && npm run seed:catalog:prod && npm run seed:admin:prod && node dist/main.js'
    plan: free
    healthCheckPath: /api/health/live
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 4000
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_SSL
        value: "true"
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: FRONTEND_URL
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: LOG_FORMAT
        value: json
